In [1]:
import numpy as np
arr = np.array([10, 20, 30, 40, 50])
print(arr)
print(type(arr))

[10 20 30 40 50]
<class 'numpy.ndarray'>


In [2]:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [3]:
import numpy as np
arr = np.array([7, 8, 9], dtype=float)
print(arr)
print(arr.dtype)

[7. 8. 9.]
float64


In [4]:
import numpy as np
arr = np.empty((2, 2))
print(arr)

[[1.63778692e-307 1.26208501e-307]
 [5.12357060e-297             nan]]


In [6]:
import numpy as np
np.random.seed(1)
arr=np.random.randint(10,size=(2,5))
print(arr)
print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.dtype)
print(arr.itemsize)
print(arr.nbytes)
print(arr[1,4])
print(arr[-1,-2])

[[5 8 9 5 0]
 [0 1 7 6 9]]
2
(2, 5)
10
int32
4
40
9
6


In [11]:
import numpy as np
np.random.seed(1)
arr=np.random.randint(10,size=(8))
print(arr)
print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.dtype)
print(arr.itemsize)
print(arr.nbytes)
print(arr[4])
print(arr[-1])

[5 8 9 5 0 0 1 7]
1
(8,)
8
int32
4
32
0
7


In [18]:
import numpy as np
np.random.seed(1)
arr1=np.random.randint(10,size=10)
print(arr1)
print(arr1[3])
print(arr1[-2])
print(arr1[3:9:2])
print(arr1[::-1])

[5 8 9 5 0 0 1 7 6 9]
5
6
[5 0 7]
[9 6 7 1 0 0 5 9 8 5]


In [20]:
import numpy as np
np.random.seed(1)
arr=np.random.randint(10,size=(2,5))
print(arr)
print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.dtype)
print(arr.itemsize)
print(arr.nbytes)
print(arr[1,4])
print(arr[-1,-2])
print(arr[:2,:3])
print(arr[1:2,:3])
print(arr[:,0])
print(arr[0,:])

[[5 8 9 5 0]
 [0 1 7 6 9]]
2
(2, 5)
10
int32
4
40
9
6
[[5 8 9]
 [0 1 7]]
[[0 1 7]]
[5 0]
[5 8 9 5 0]


In [5]:
#8
import numpy as np
arr = np.arange(1, 21)
print("Array:", arr)
print("Number of dimensions:", arr.ndim)
print("Shape:", arr.shape)
print("Size:", arr.size)
print("Data type:", arr.dtype)

Array: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
Number of dimensions: 1
Shape: (20,)
Size: 20
Data type: int32


In [6]:
#10
import numpy as np
arr = np.arange(1, 13).reshape(3, 4)
print(arr)
print("Row 2, Column 3:", arr[1, 2])
print("Last row:", arr[-1])
print("Last column:", arr[:, -1])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Row 2, Column 3: 7
Last row: [ 9 10 11 12]
Last column: [ 4  8 12]


In [7]:
#9
import numpy as np
np.random.seed(0)
arr = np.random.randint(0, 51, size=(4, 5))
print("Array:")
print(arr)
print("Item size:", arr.itemsize)
print("Number of bytes:", arr.nbytes)

Array:
[[44 47  0  3  3]
 [39  9 19 21 50]
 [36 23  6 24 24]
 [12  1 38 39 23]]
Item size: 4
Number of bytes: 80


In [8]:
#15
import numpy as np
arr = np.arange(1, 16)
parts = np.split(arr, 3)
print("Original array:", arr)
print("Part 1:", parts[0])
print("Part 2:", parts[1])
print("Part 3:", parts[2])

Original array: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
Part 1: [1 2 3 4 5]
Part 2: [ 6  7  8  9 10]
Part 3: [11 12 13 14 15]
